server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://180.76.52.59:3306/scan?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: scan
    password: QQ@1607247596

mybatis-plus:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl